services:
  movies:
    build: ./app
    command: python movie_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/movie_project: /usr/src/app/
    ports:
      - 8009:8000

    env_file:
      - ./app/ .env.dev
