services:
  movies:
    build: .
    command: bash -c "python movie_project/manage.py makemigrations && python movie_project/manage.py migrate && python movie_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000

    env_file:
      - ./app/.env.development

    environment:
      - DJANGO_ENVIRONMENT=development
      - PYTHONPATH=/usr/src/app

    depends_on:
      - movies-db

  movies-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=movies
      - POSTGRES_DB=movies_dev

volumes:
  postgres_data:
